using Orchard.ContentManagement;
using Orchard.ContentManagement.Utilities;

// This code was generated by Orchardizer

namespace Mod.Twilio.Models
{
    public class TwilioSettingsPart : ContentPart {
        private readonly ComputedField<string> _authToken = new ComputedField<string>();

        public string AccountSID {
            get { return this.Retrieve(x => x.AccountSID); }
            set { this.Store(x => x.AccountSID, value); }
        }

        public string AuthToken {
            get { return _authToken.Value; }
            set { _authToken.Value = value; }
        }

        public ComputedField<string> AuthTokenField {
            get { return _authToken; }
        }

        public string FromNumber {
            get { return this.Retrieve(x => x.FromNumber); }
            set { this.Store(x => x.FromNumber, value); }
        }

    }
}